version: '3.3'
services:
  nginx:
    image: nginx
    depends_on:
      - nodejs
      - tomcat
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    ports:
      - 5433:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  nodejs:
    image: node
    working_dir: /app
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app
    ports:
      - 3000:3000
    command: bash -c "npm i && npm i -g nodemon && nodemon server.js"

  tomcat:
    image: tomcat:8-jre11
    depends_on:
      - postgis
    volumes:
      - ./tomcat/:/usr/local/tomcat/webapps/
      - ./tomcat/fonts/truetype/:/usr/share/fonts/truetype/
    ports:
      - 8080:8080
